name: Draft Release

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: read

concurrency:
  group: draft-release-main
  cancel-in-progress: true

jobs:
  update-release-draft:
    name: Update release draft
    runs-on: ubuntu-latest

    steps:
      - name: Update draft release notes
        uses: release-drafter/release-drafter@v7
        with:
          config-name: release-drafter.yml
